services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: madocs
    ports:
      - "5435:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/madocs
      - SECRET_KEY=dev-secret-change-me
      # LLM config (pick one provider)
      - AZURE_OPENAI_ENDPOINT=
      - AZURE_OPENAI_API_KEY=
      - AZURE_OPENAI_DEPLOYMENT=gpt-4o
      - OPENAI_API_KEY=
      - OPENAI_MODEL=gpt-4o-mini
      - OPENAI_EMBED_MODEL=text-embedding-3-large
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:8000
      - VITE_WS_BASE=ws://localhost:8000
    ports:
      - "5173:80"

volumes:
  dbdata:
  backend_data:
